DROP TABLE IF EXISTS finance_economic_data;

CREATE TABLE finance_economic_data (
    "Date"                                  DATE,
    "Stock Index"                           VARCHAR(50),
    "Open Price"                            FLOAT,
    "Close Price"                           FLOAT,
    "Daily High"                            FLOAT,
    "Daily Low"                             FLOAT,
    "Trading Volume"                        FLOAT,
    "GDP Growth (%)"                        FLOAT,
    "Inflation Rate (%)"                    FLOAT,
    "Unemployment Rate (%)"                 FLOAT,
    "Interest Rate (%)"                     FLOAT,
    "Consumer Confidence Index"             FLOAT,
    "Government Debt (Billion USD)"         FLOAT,
    "Corporate Profits (Billion USD)"       FLOAT,
    "Forex USD/EUR"                         FLOAT,
    "Forex USD/JPY"                         FLOAT,
    "Crude Oil Price (USD per Barrel)"      FLOAT,
    "Gold Price (USD per Ounce)"            FLOAT,
    "Real Estate Index"                     FLOAT,
    "Retail Sales (Billion USD)"            FLOAT,
    "Bankruptcy Rate (%)"                   FLOAT,
    "Mergers & Acquisitions Deals"          FLOAT,
    "Venture Capital Funding (Billion USD)" FLOAT,
    "Consumer Spending (Billion USD)"       FLOAT,
    "Daily_Return (%)"                      FLOAT,
    "Misery_Index"                          FLOAT,
    "Real_Interest_Rate (%)"                FLOAT,
    "Volatility_Band (%)"                   FLOAT,
    "Economic_Health_Score"                 FLOAT,
    "Stock_Index_encoded"                   INTEGER,
    "Year"                                  INTEGER,
    "Month"                                 INTEGER,
    "Quarter"                               INTEGER,
    "Month_Name"                            VARCHAR(10)
);